name: 'Azure AD Workload Identity Federation'
description: 'Acquire access tokens for app registrations with workload identity federation enabled.'
branding:
  icon: 'server'
  color: 'blue'
inputs:
  tenant_id: 
    description: 'Azure AD Tenant ID'
    required: true
    default: '30204efd-acb7-41a7-9fe9-233cec0556c1'
  client_id: 
    description: 'App Registration Client ID'
    required: true
    default: '960d282a-7d02-453e-a680-3b4330ed38a7'
  audience:
    description: 'OIDC audience'
    required: false
    default: 'api://AzureADTokenExchange'
  scope:
    description: 'OIDC Scope'
    required: false
    default: 'https://graph.microsoft.com/.default'
outputs:
  access_token:
    description: 'Azure AD JWT for the assigned application permissions'
runs:
  using: 'node16'
  main: 'dist/index.js'